#!/bin/bash
set -e

die () {
    echo
    echo "$*"
    echo
    exit 1
}

usage () {
    die "Usage: release <(core|annotations)> <version>"
}

MODULE="$1"
VERSION="$2"
PREFIX=""

if [[ "$MODULE" != "core" ]] && [[ "$MODULE" != "annotations" ]]; then
  usage
fi

if [[ "$MODULE" == "core" ]]; then
  PREFIX="v"
else
  PREFIX="a"
fi

if [[ -z "$VERSION" ]]; then
  usage
fi

git checkout master
git pull origin master
./gradlew -Pversion=${VERSION} ${MODULE}:clean ${MODULE}:test ${MODULE}:publish

read -e -p "Upload successful. Also tag? [y/N]"
if [[ "$REPLY" == [Yy]* ]]; then
  git tag "${PREFIX}${VERSION}"
  git push origin --tags
fi

