#!/bin/bash

die () {
    echo "$*"
    exit 1
}

usage="Usage: release <version>"

if [[ `git status --porcelain` ]]; then
  die "dirty workspace"
fi

VERSION="$1"

if [[ -z "$VERSION" ]]; then
  die "$usage"
fi

git pull origin $(git rev-parse --abbrev-ref HEAD) || die "pull failed"
./gradlew clean -Pversion=${VERSION} jbock:publish || die "build failed"
./gradlew clean -Pversion=${VERSION} compiler:publish || die "build failed"

read -e -p "Upload successful. Also tag? [y/N]"
if [[ "$REPLY" == [Yy]* ]]; then
  git tag "${VERSION}"
  git push origin --tags
fi

