#!/bin/bash
if [[ -z "$1" ]]; then echo arg: version; exit 1; fi
mvn versions:set -DnewVersion=$1 &>/dev/null
if [[ "$1" =~ .*SNAPSHOT ]]; then
  mvn clean install
else
  mvn clean install -Psonatype-oss-release
fi
cp pom.xml target/jbock-annotations-$1.pom
mv pom.xml.versionsBackup pom.xml
