#!/bin/bash
# 1. Define this key in ~/.gradle/gradle.properties: signing.secretKeyRingFile (full path to exported keyring, no ascii armor)
# 2. Source / export these environment variables: OSS_USER, OSS_PASS (login for http://oss.sonatype.org/)
# 3. Source / export these environment variables: SIGNING_KEY_ID, SIGNING_PASSWORD
set -e

if [[ -z "$1" ]]; then echo "arg: version;" exit 1; fi
gradle "-Pversion=${1}" clean test uploadArchives 

read -e -p "Upload successful. Also tag? [y/N]"
if [[ "$REPLY" == [Yy]* ]]; then
  git tag "v${1}"
  git push origin --tags
fi

