#!/bin/bash

function compile() {
  javac -source 9 \
    -cp ../core/target/jbock-0-SNAPSHOT.jar \
    -d target/classes \
    -s target/generated-sources/annotations \
    $1
}

for S in `find src/main/java/net -name "*.java"`; do
  compile $S
done
