package net.jbock.compiler.view;

import com.squareup.javapoet.CodeBlock;
import net.jbock.scope.ContextScope;

import javax.inject.Inject;

@ContextScope
public class ClassJavadoc {

  private static final String PROJECT_URL = "https://github.com/h908714124/jbock";

  @Inject
  ClassJavadoc() {
  }

  CodeBlock create() {
    String version = getClass().getPackage().getImplementationVersion();
    return CodeBlock.of("<h3>Generated by <a href=$S>jbock $L</a></h3>", PROJECT_URL, version);
  }
}
